//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Curs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int IdBook { get; set; }
        public string NameBook { get; set; }
        public string Author { get; set; }
        public string Publication { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Genre { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<int> Format { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Evaluation { get; set; }
        public string Review { get; set; }
        public Nullable<int> IdYear { get; set; }
        public string Image { get; set; }
    
        public virtual Evaluations Evaluations { get; set; }
        public virtual Formats Formats { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual statuses statuses { get; set; }
        public virtual Years Years { get; set; }
    }
}
